CREATE TABLE MOONS (
ID INT PRIMARY KEY,
MOON_NAME VARCHAR2(60),
PLANET_ID INT 
);
/
CREATE TABLE PLANETS (
PLANET_ID INT PRIMARY KEY,
PLANET_NAME VARCHAR2(60),
PLANET_LOCATION VARCHAR2(60)
);
/
ALTER TABLE MOONS
ADD CONSTRAINT FK_PLANET_ID
FOREIGN KEY (PLANET_ID) REFERENCES PLANETS(PLANET_ID);
